@startuml sampledb.er
	entity genders {
		id: SERIAL NOT NULL PRIMARY KEY,
		name: VARCHAR(1)
	}

	entity roles {
		code: SERIAL NOT NULL PRIMARY KEY,
		name: VARCHAR(10)
	}

	entity users {
		id: SERIAL NOT NULL PRIMARY KEY,
		name: VARCHAR(20) NOT NULL,
		email: VARCHAR(255) NOT NULL UNIQUE,
		handler: VARCHAR(10),
		role: INTEGER NOT NULL
	}



@enduml