@startuml gotoLogin
	actor User as client
	boundary Dispatcher as dp
	control AuthController as ac
	participant AuthService as as
	
	group <font color="Navy">一般ユーザとしてアクセスする場合
		||7||
		client -> dp: URLにアクセス\n[GET] /app
		activate dp
		dp  -> ac: index(role: int = 1): String
		activate ac
		ac --> as: showLogin(role: int = 1): String
		activate as
		ac <-- as: "auth/login"
		deactivate as
		ac --> dp: "auth/login"
		deactivate ac
		dp  -> dp: model.addAttribute("role", 1)
		dp --> client: "auth/login"
		deactivate dp
		||10||
	end

	||20||

	group <font color="Navy">管理者ユーザとしてアクセスする場合
		||7||
		client -> dp: URLにアクセス\n[GET] /app/admin
		activate dp
		dp  -> ac: index(model): String
		activate ac
		ac --> as: showLogin(0): String
		activate as
		ac <-- as: "admin/login"
		deactivate as
		ac --> dp: "admin/login"
		deactivate ac
		dp  -> dp: mode.addAttribute("mode", 0)
		dp --> client: "admin/login"
		deactivate dp
		||10||
	end
	||10||
@enduml